service:
  name: wiretap-spike

plugins:
  - serverless-webpack
  - serverless-pseudo-parameters
  - serverless-offline
  - serverless-plugin-aws-alerts

provider:
  name: aws
  runtime: nodejs8.10
  tracing:
    lambda: true

custom:
  httpservice:
    url: ${opt:httpServiceUrl}
  proxy:
    url: ${opt:proxyUrl}
    timeout: ${opt:proxyTimeout}
  vpc:
    id: ${opt:vpcId}
    subnets:
      private: ${opt:privateSubnetIds}
      public: ${opt:publicSubnetIds}
  wiretap:
    port: 5050
    s3Logs: traffic-tee-logs-${self:provider.stage}
  alerts:
    dashboards: true
    alarms:
      - functionThrottles
      - functionErrors
      - functionInvocations
      - functionDuration

functions:
  sendProxy:
    handler: build/handler.sendProxy
    timeout: 30
    vpc:
      securityGroupIds:
        - Ref: sendProxySecurityGroup
      subnetIds: !Split [",", "${self:custom.vpc.subnets.private}"]
    environment:
      PROXY_URL: ${self:custom.proxy.url}
      PROXY_TIMEOUT_SECONDS: ${self:custom.proxy.timeout}
      PROXY_BUCKET_NAME: ${self:custom.wiretap.s3Logs}

  proxyToHttpService:
    handler: build/handler.proxyToHttpService
    vpc:
      securityGroupIds:
        - Ref: proxyToHttpServiceSecurityGroup
      subnetIds: !Split [",", "${self:custom.vpc.subnets.private}"]
    environment:
      HTTP_SERVICE_URL: ${self:custom.httpservice.url}
    events:
      - s3:
          bucket: ${self:custom.wiretap.s3Logs}
          event: s3:ObjectCreated:*

resources:
  Resources:
    proxyToHttpServiceSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        VpcId: ${self:custom.vpc.id}
        GroupDescription: "Lambda Security Group for proxyToHttpService function"

    sendProxySecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupName: SendProxySecurityGroup
        GroupDescription: "Lambda Security Group for sendProxy function"
        VpcId: ${self:custom.vpc.id}
        SecurityGroupIngress:
          - SourceSecurityGroupId: !Ref albSecurityGroupSendProxy
            IpProtocol: tcp
            FromPort: ${self:custom.wiretap.port}
            ToPort: ${self:custom.wiretap.port}

    albSecurityGroupSendProxy:
      Type: AWS::EC2::SecurityGroup
      Properties:
        VpcId: ${self:custom.vpc.id}
        GroupName: "SendProxyALBSecurityGroup"
        GroupDescription: "ALB Security Group to define allowed traffic"
        SecurityGroupIngress:
          - CidrIp: 0.0.0.0/0
            IpProtocol: tcp
            FromPort: ${self:custom.wiretap.port}
            ToPort: ${self:custom.wiretap.port}

    albService:
      Type: AWS::ElasticLoadBalancingV2::LoadBalancer
      Properties:
        Type: application
        Scheme: internet-facing
        IpAddressType: ipv4
        Subnets: !Split [",", "${self:custom.vpc.subnets.public}"]
        SecurityGroups:
          - !Ref albSecurityGroupSendProxy

    albListenerSendProxy:
      Type: AWS::ElasticLoadBalancingV2::Listener
      Properties:
        Port: ${self:custom.wiretap.port}
        LoadBalancerArn: !Ref albService
        Protocol: HTTP
        DefaultActions:
          - Type: forward
            TargetGroupArn: !Ref sendProxyTargetGroup

    sendProxyInvocationELBPermission:
      Type: AWS::Lambda::Permission
      Properties:
        Action: lambda:InvokeFunction
        FunctionName: !GetAtt SendProxyLambdaFunction.Arn
        Principal: elasticloadbalancing.amazonaws.com
        SourceArn: arn:aws:elasticloadbalancing:#{AWS::Region}:#{AWS::AccountId}:targetgroup/*

    sendProxyTargetGroup:
      Type: AWS::ElasticLoadBalancingV2::TargetGroup
      Properties:
        TargetType: lambda
        Targets:
          - Id: !GetAtt SendProxyLambdaFunction.Arn

    trafficTeeLogS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: ${self:custom.wiretap.s3Logs}
        PolicyDocument:
          Statement:
            - Effect: 'Allow'
              Action:
                - s3:PutObject
                - s3:GetObject
              Resource: arn:aws:s3:::${self:custom.wiretap.s3Logs}/*
              Principal:
                AWS: !GetAtt IamRoleLambdaExecution.Arn

  Outputs:
    serviceElbDnsName:
      Value: !GetAtt albService.DNSName
      Export:
        Name:
          Fn::Join:
            - '-'
            - - Ref: "AWS::StackName"
              - "serviceElbDnsName"

    sendProxyFunctionName:
      Value: !GetAtt SendProxyLambdaFunction.Arn
      Export:
        Name:
          Fn::Join:
            - '-'
            - - Ref: "AWS::StackName"
              - "sendProxyFunction"
