service:
  name: aws-nodejs-typescript

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          method: get
          path: hello

resources:  # CloudFormation template syntax
  Resources:
